pipeline {

	agent any
	
	stages {
		
		stage("Git pull") {
			
			steps {
				
				git branch : 'main', credentialsId: 'git_creds', url: 'https://github.com/saiprakashmarella/sampleGradlle'
			}
		}
		
		stage("Build"){
			
			steps {
				
				sh './gradlew clean build'
			}
		}
	}
}